/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as BrandsVSunRouteImport } from './routes/brands.v-sun'
import { Route as BrandsYesenTechnologiesRouteImport } from './routes/brands.yesen-technologies'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsBKoolRouteImport } from './routes/products.b-kool'
import { Route as ProductsEMarineRouteImport } from './routes/products.e-marine'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'
import { Route as SolutionsMarineElectrificationRouteImport } from './routes/solutions_.marine-electrification'
import { Route as SolutionsShoreInfrastructureRouteImport } from './routes/solutions_.shore-infrastructure'
import { Route as SolutionsSmartConnectedMarineSystemsRouteImport } from './routes/solutions_.smart-connected-marine-systems'
import { Route as SolutionsSolarIntegrationRouteImport } from './routes/solutions_.solar-integration'
import { Route as SolutionsTourismHospitalityRouteImport } from './routes/solutions_.tourism-hospitality'
import { Route as SolutionsVesselEngineeringConstructionRouteImport } from './routes/solutions_.vessel-engineering-construction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsVSunRoute = BrandsVSunRouteImport.update({
  id: '/brands/v-sun',
  path: '/brands/v-sun',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsYesenTechnologiesRoute = BrandsYesenTechnologiesRouteImport.update({
  id: '/brands/yesen-technologies',
  path: '/brands/yesen-technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBKoolRoute = ProductsBKoolRouteImport.update({
  id: '/products/b-kool',
  path: '/products/b-kool',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEMarineRoute = ProductsEMarineRouteImport.update({
  id: '/products/e-marine',
  path: '/products/e-marine',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsMarineElectrificationRoute =
  SolutionsMarineElectrificationRouteImport.update({
    id: '/solutions_/marine-electrification',
    path: '/solutions/marine-electrification',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsShoreInfrastructureRoute =
  SolutionsShoreInfrastructureRouteImport.update({
    id: '/solutions_/shore-infrastructure',
    path: '/solutions/shore-infrastructure',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsSmartConnectedMarineSystemsRoute =
  SolutionsSmartConnectedMarineSystemsRouteImport.update({
    id: '/solutions_/smart-connected-marine-systems',
    path: '/solutions/smart-connected-marine-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsSolarIntegrationRoute =
  SolutionsSolarIntegrationRouteImport.update({
    id: '/solutions_/solar-integration',
    path: '/solutions/solar-integration',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsTourismHospitalityRoute =
  SolutionsTourismHospitalityRouteImport.update({
    id: '/solutions_/tourism-hospitality',
    path: '/solutions/tourism-hospitality',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsVesselEngineeringConstructionRoute =
  SolutionsVesselEngineeringConstructionRouteImport.update({
    id: '/solutions_/vessel-engineering-construction',
    path: '/solutions/vessel-engineering-construction',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRoute
  '/brands/v-sun': typeof BrandsVSunRoute
  '/brands/yesen-technologies': typeof BrandsYesenTechnologiesRoute
  '/products/b-kool': typeof ProductsBKoolRoute
  '/products/e-marine': typeof ProductsEMarineRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/solutions/marine-electrification': typeof SolutionsMarineElectrificationRoute
  '/solutions/shore-infrastructure': typeof SolutionsShoreInfrastructureRoute
  '/solutions/smart-connected-marine-systems': typeof SolutionsSmartConnectedMarineSystemsRoute
  '/solutions/solar-integration': typeof SolutionsSolarIntegrationRoute
  '/solutions/tourism-hospitality': typeof SolutionsTourismHospitalityRoute
  '/solutions/vessel-engineering-construction': typeof SolutionsVesselEngineeringConstructionRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRoute
  '/brands/v-sun': typeof BrandsVSunRoute
  '/brands/yesen-technologies': typeof BrandsYesenTechnologiesRoute
  '/products/b-kool': typeof ProductsBKoolRoute
  '/products/e-marine': typeof ProductsEMarineRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/solutions/marine-electrification': typeof SolutionsMarineElectrificationRoute
  '/solutions/shore-infrastructure': typeof SolutionsShoreInfrastructureRoute
  '/solutions/smart-connected-marine-systems': typeof SolutionsSmartConnectedMarineSystemsRoute
  '/solutions/solar-integration': typeof SolutionsSolarIntegrationRoute
  '/solutions/tourism-hospitality': typeof SolutionsTourismHospitalityRoute
  '/solutions/vessel-engineering-construction': typeof SolutionsVesselEngineeringConstructionRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRoute
  '/brands/v-sun': typeof BrandsVSunRoute
  '/brands/yesen-technologies': typeof BrandsYesenTechnologiesRoute
  '/products/b-kool': typeof ProductsBKoolRoute
  '/products/e-marine': typeof ProductsEMarineRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/solutions_/marine-electrification': typeof SolutionsMarineElectrificationRoute
  '/solutions_/shore-infrastructure': typeof SolutionsShoreInfrastructureRoute
  '/solutions_/smart-connected-marine-systems': typeof SolutionsSmartConnectedMarineSystemsRoute
  '/solutions_/solar-integration': typeof SolutionsSolarIntegrationRoute
  '/solutions_/tourism-hospitality': typeof SolutionsTourismHospitalityRoute
  '/solutions_/vessel-engineering-construction': typeof SolutionsVesselEngineeringConstructionRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/enquire'
    | '/faq'
    | '/legal'
    | '/projects'
    | '/solutions'
    | '/brands/v-sun'
    | '/brands/yesen-technologies'
    | '/products/b-kool'
    | '/products/e-marine'
    | '/projects/$projectId'
    | '/solutions/marine-electrification'
    | '/solutions/shore-infrastructure'
    | '/solutions/smart-connected-marine-systems'
    | '/solutions/solar-integration'
    | '/solutions/tourism-hospitality'
    | '/solutions/vessel-engineering-construction'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/enquire'
    | '/faq'
    | '/legal'
    | '/projects'
    | '/solutions'
    | '/brands/v-sun'
    | '/brands/yesen-technologies'
    | '/products/b-kool'
    | '/products/e-marine'
    | '/projects/$projectId'
    | '/solutions/marine-electrification'
    | '/solutions/shore-infrastructure'
    | '/solutions/smart-connected-marine-systems'
    | '/solutions/solar-integration'
    | '/solutions/tourism-hospitality'
    | '/solutions/vessel-engineering-construction'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/enquire'
    | '/faq'
    | '/legal'
    | '/projects'
    | '/solutions'
    | '/brands/v-sun'
    | '/brands/yesen-technologies'
    | '/products/b-kool'
    | '/products/e-marine'
    | '/projects_/$projectId'
    | '/solutions_/marine-electrification'
    | '/solutions_/shore-infrastructure'
    | '/solutions_/smart-connected-marine-systems'
    | '/solutions_/solar-integration'
    | '/solutions_/tourism-hospitality'
    | '/solutions_/vessel-engineering-construction'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  EnquireRoute: typeof EnquireRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  ProjectsRoute: typeof ProjectsRoute
  SolutionsRoute: typeof SolutionsRoute
  BrandsVSunRoute: typeof BrandsVSunRoute
  BrandsYesenTechnologiesRoute: typeof BrandsYesenTechnologiesRoute
  ProductsBKoolRoute: typeof ProductsBKoolRoute
  ProductsEMarineRoute: typeof ProductsEMarineRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SolutionsMarineElectrificationRoute: typeof SolutionsMarineElectrificationRoute
  SolutionsShoreInfrastructureRoute: typeof SolutionsShoreInfrastructureRoute
  SolutionsSmartConnectedMarineSystemsRoute: typeof SolutionsSmartConnectedMarineSystemsRoute
  SolutionsSolarIntegrationRoute: typeof SolutionsSolarIntegrationRoute
  SolutionsTourismHospitalityRoute: typeof SolutionsTourismHospitalityRoute
  SolutionsVesselEngineeringConstructionRoute: typeof SolutionsVesselEngineeringConstructionRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/v-sun': {
      id: '/brands/v-sun'
      path: '/brands/v-sun'
      fullPath: '/brands/v-sun'
      preLoaderRoute: typeof BrandsVSunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/yesen-technologies': {
      id: '/brands/yesen-technologies'
      path: '/brands/yesen-technologies'
      fullPath: '/brands/yesen-technologies'
      preLoaderRoute: typeof BrandsYesenTechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/b-kool': {
      id: '/products/b-kool'
      path: '/products/b-kool'
      fullPath: '/products/b-kool'
      preLoaderRoute: typeof ProductsBKoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/e-marine': {
      id: '/products/e-marine'
      path: '/products/e-marine'
      fullPath: '/products/e-marine'
      preLoaderRoute: typeof ProductsEMarineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/marine-electrification': {
      id: '/solutions_/marine-electrification'
      path: '/solutions/marine-electrification'
      fullPath: '/solutions/marine-electrification'
      preLoaderRoute: typeof SolutionsMarineElectrificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/shore-infrastructure': {
      id: '/solutions_/shore-infrastructure'
      path: '/solutions/shore-infrastructure'
      fullPath: '/solutions/shore-infrastructure'
      preLoaderRoute: typeof SolutionsShoreInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/smart-connected-marine-systems': {
      id: '/solutions_/smart-connected-marine-systems'
      path: '/solutions/smart-connected-marine-systems'
      fullPath: '/solutions/smart-connected-marine-systems'
      preLoaderRoute: typeof SolutionsSmartConnectedMarineSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/solar-integration': {
      id: '/solutions_/solar-integration'
      path: '/solutions/solar-integration'
      fullPath: '/solutions/solar-integration'
      preLoaderRoute: typeof SolutionsSolarIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/tourism-hospitality': {
      id: '/solutions_/tourism-hospitality'
      path: '/solutions/tourism-hospitality'
      fullPath: '/solutions/tourism-hospitality'
      preLoaderRoute: typeof SolutionsTourismHospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/vessel-engineering-construction': {
      id: '/solutions_/vessel-engineering-construction'
      path: '/solutions/vessel-engineering-construction'
      fullPath: '/solutions/vessel-engineering-construction'
      preLoaderRoute: typeof SolutionsVesselEngineeringConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  EnquireRoute: EnquireRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  ProjectsRoute: ProjectsRoute,
  SolutionsRoute: SolutionsRoute,
  BrandsVSunRoute: BrandsVSunRoute,
  BrandsYesenTechnologiesRoute: BrandsYesenTechnologiesRoute,
  ProductsBKoolRoute: ProductsBKoolRoute,
  ProductsEMarineRoute: ProductsEMarineRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SolutionsMarineElectrificationRoute: SolutionsMarineElectrificationRoute,
  SolutionsShoreInfrastructureRoute: SolutionsShoreInfrastructureRoute,
  SolutionsSmartConnectedMarineSystemsRoute:
    SolutionsSmartConnectedMarineSystemsRoute,
  SolutionsSolarIntegrationRoute: SolutionsSolarIntegrationRoute,
  SolutionsTourismHospitalityRoute: SolutionsTourismHospitalityRoute,
  SolutionsVesselEngineeringConstructionRoute:
    SolutionsVesselEngineeringConstructionRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
